remote_theme: pages-themes/cayman@v0.2.0
title: Deep Learning Portfolio
description: Welcome! I am Anna-Lena Wörpel, a masters student in computer science and specializing in scientific computing and visualization. Currently, I want to learn more about deep learning as I want to work in this field later.
