remote_theme: pages-themes/cayman@v0.2.0
title: Data Science Portfolio
description: Welcome! I am Anna-Lena Wörpel, a Computer Science student specializing in Scientific Computing and Visualization. Currently, I want to learn more about Data Science as I want to work in this field later.
